+incdir+../dut
+incdir+../tb/if
+incdir+../tb/agents/ita_ctrl_agent
+incdir+../tb/agents/ita_stream_agent
+incdir+../tb/scb
+incdir+../tb/env
+incdir+../tb/seq
+incdir+../tb/tests

../dut/cf_math_pkg.sv
../dut/tc_clk.sv
../dut/cluster_clk_cells.sv
../dut/fifo_v3.sv
../dut/tc_sram.sv
../dut/lzc.sv
../dut/ita_package.sv
../dut/ita_register_file_1w_multi_port_read.sv
../dut/ita_register_file_1w_multi_port_read_we.sv
../dut/ita_register_file_1w_1r_double_width_write.sv
../dut/ita_dotp.sv
../dut/ita_sumdotp.sv
../dut/ita_accumulator.sv
../dut/ita_relu.sv
../dut/ita_gelu.sv
../dut/ita_activation.sv
../dut/ita_requantization_controller.sv
../dut/ita_requantizer.sv
../dut/ita_max_finder.sv
../dut/ita_serdiv.sv
../dut/ita_softmax.sv
../dut/ita_softmax_top.sv
../dut/ita_fifo_controller.sv
../dut/ita_output_controller.sv
../dut/ita_input_sampler.sv
../dut/ita_inp1_mux.sv
../dut/ita_inp2_mux.sv
../dut/ita_weight_controller.sv
../dut/ita_controller.sv
../dut/ita.sv
../dut/ita_head_sum.sv
../dut/ita_mha8.sv

../tb/if/ita_mha8_if.sv
../tb/agents/ita_ctrl_agent/ita_ctrl_agent_pkg.sv
../tb/agents/ita_stream_agent/ita_stream_agent_pkg.sv
../tb/scb/ita_mha8_scb_pkg.sv
../tb/env/ita_mha8_env_pkg.sv
../tb/seq/ita_mha8_seq_pkg.sv
../tb/tests/ita_mha8_test_pkg.sv
../tb/top/ita_mha8_tb_top.sv
