+incdir+../dut
+incdir+../tbak/if
+incdir+../tbak/agents/ita_ctrl_agent
+incdir+../tbak/agents/ita_stream_agent
+incdir+../tbak/log
+incdir+../tbak/common
+incdir+../tbak/env
+incdir+../tbak/seq
+incdir+../tbak/vseq
+incdir+../tbak/tests

../dut/cf_math_pkg.sv
../dut/tc_clk.sv
../dut/cluster_clk_cells.sv
../dut/fifo_v3.sv
../dut/tc_sram.sv
../dut/lzc.sv
../dut/ita_package.sv
../dut/ita_register_file_1w_multi_port_read.sv
../dut/ita_register_file_1w_multi_port_read_we.sv
../dut/ita_register_file_1w_1r_double_width_write.sv
../dut/ita_dotp.sv
../dut/ita_sumdotp.sv
../dut/ita_accumulator.sv
../dut/ita_relu.sv
../dut/ita_gelu.sv
../dut/ita_activation.sv
../dut/ita_requantization_controller.sv
../dut/ita_requantizer.sv
../dut/ita_max_finder.sv
../dut/ita_serdiv.sv
../dut/ita_softmax.sv
../dut/ita_softmax_top.sv
../dut/ita_fifo_controller.sv
../dut/ita_output_controller.sv
../dut/ita_input_sampler.sv
../dut/ita_inp1_mux.sv
../dut/ita_inp2_mux.sv
../dut/ita_weight_controller.sv
../dut/ita_controller.sv
../dut/ita.sv
../dut/ita_head_sum.sv
../dut/ita_mha8.sv

../tbak/if/ita_mha8_if.sv
../tbak/agents/ita_ctrl_agent/ita_ctrl_agent_pkg.sv
../tbak/agents/ita_stream_agent/ita_stream_agent_pkg.sv
../tbak/log/ita_mha8_log_pkg.sv
../tbak/common/ita_mha8_common_pkg.sv
../tbak/env/ita_mha8_env_pkg.sv
../tbak/seq/ita_mha8_seq_pkg.sv
../tbak/vseq/ita_mha8_vseq_pkg.sv
../tbak/tests/ita_mha8_test_pkg.sv
../tbak/top/ita_mha8_tb_top.sv
