#!/usr/bin/env python3
# Copyright 2026
# SPDX-License-Identifier: Apache-2.0

"""Run the Stage 10 head0 Linear offline compare flow.

Default flow:
  1. Parse UVM logger CSV into a hexadecimal actual txt.
  2. Compare the parsed actual txt with an expected txt.

The defaults match the tbak Linear directed smoke test:
  - input CSV:    ITA_CORE_UVM/sim/logger/ita_mha8_output.csv
  - expected txt: ITA_CORE_UVM/sim/logger/expected_matmul_head0.txt
  - actual txt:   ITA_CORE_UVM/sim/logger/actual_matmul_head0.txt
  - phase:        MatMul
  - stream:       per_head
  - head:         0
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def core_root() -> Path:
    return Path(__file__).resolve().parents[2]


def tool_dir() -> Path:
    return Path(__file__).resolve().parent


def run(cmd: list[str], dry_run: bool) -> None:
    print("PY> " + " ".join(cmd), flush=True)
    if not dry_run:
        subprocess.run(cmd, check=True)


def main() -> int:
    root = core_root()
    logger_dir = root / "sim" / "logger"

    parser = argparse.ArgumentParser(description="Parse and compare tbak Linear head0 actual output.")
    parser.add_argument(
        "--actual-csv",
        type=Path,
        default=logger_dir / "ita_mha8_output.csv",
        help="UVM logger CSV generated by ita_mha8_logger.",
    )
    parser.add_argument(
        "--expected",
        type=Path,
        default=logger_dir / "expected_matmul_head0.txt",
        help="Expected hexadecimal txt file.",
    )
    parser.add_argument(
        "--actual-txt",
        type=Path,
        default=logger_dir / "actual_matmul_head0.txt",
        help="Parsed actual hexadecimal txt file to create before compare.",
    )
    parser.add_argument("--phase", default="MatMul", help="Output phase/step to parse from the CSV.")
    parser.add_argument("--stream", default="per_head", help="Output stream to parse from the CSV.")
    parser.add_argument("--head", type=int, default=0, help="Head id to parse from the CSV.")
    parser.add_argument("--bit-width", type=int, help="Optional bit width forwarded to compare.py.")
    parser.add_argument("--row-words", type=int, default=1, help="Values per row forwarded to compare.py.")
    parser.add_argument("--dry-run", action="store_true", help="Print commands without executing them.")
    args = parser.parse_args()

    parse_cmd = [
        sys.executable,
        str(tool_dir() / "parse_actual.py"),
        "--input",
        str(args.actual_csv),
        "--format",
        "uvm-csv",
        "--phase",
        args.phase,
        "--stream",
        args.stream,
        "--head",
        str(args.head),
        "--out",
        str(args.actual_txt),
    ]

    compare_cmd = [
        sys.executable,
        str(tool_dir() / "compare.py"),
        "--expected",
        str(args.expected),
        "--actual",
        str(args.actual_txt),
        "--row-words",
        str(args.row_words),
    ]
    if args.bit_width is not None:
        compare_cmd.extend(["--bit-width", str(args.bit_width)])

    run(parse_cmd, args.dry_run)
    run(compare_cmd, args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


