#!/usr/bin/env python3
# Copyright 2026
# SPDX-License-Identifier: Apache-2.0

"""Run the Stage 10 Linear per-head offline compare flow.

Default flow:
  1. For each head, parse UVM logger CSV into actual_matmul_head<N>.txt.
  2. Compare it with expected_matmul_head<N>.txt.

Defaults match the tbak Linear directed smoke test and now cover heads 0-7.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def core_root() -> Path:
    return Path(__file__).resolve().parents[2]


def tool_dir() -> Path:
    return Path(__file__).resolve().parent


def run(cmd: list[str], dry_run: bool) -> None:
    print("PY> " + " ".join(cmd), flush=True)
    if not dry_run:
        subprocess.run(cmd, check=True)


def main() -> int:
    root = core_root()
    logger_dir = root / "sim" / "logger"

    parser = argparse.ArgumentParser(description="Parse and compare tbak Linear actual output per head.")
    parser.add_argument(
        "--actual-csv",
        type=Path,
        default=logger_dir / "ita_mha8_output.csv",
        help="UVM logger CSV generated by ita_mha8_logger.",
    )
    parser.add_argument("--expected-prefix", default="expected_matmul_head", help="Expected filename prefix.")
    parser.add_argument("--actual-prefix", default="actual_matmul_head", help="Actual filename prefix.")
    parser.add_argument("--dir", type=Path, default=logger_dir, help="Directory containing expected and actual txt files.")
    parser.add_argument("--heads", type=int, default=8, help="Number of heads to compare, starting at head 0.")
    parser.add_argument("--phase", default="MatMul", help="Output phase/step to parse from the CSV.")
    parser.add_argument("--stream", default="per_head", help="Output stream to parse from the CSV.")
    parser.add_argument("--bit-width", type=int, help="Optional bit width forwarded to compare.py.")
    parser.add_argument("--row-words", type=int, default=1, help="Values per row forwarded to compare.py.")
    parser.add_argument("--dry-run", action="store_true", help="Print commands without executing them.")
    args = parser.parse_args()

    if args.heads <= 0 or args.heads > 8:
        raise ValueError("--heads must be in the range 1..8")

    for head in range(args.heads):
        expected = args.dir / f"{args.expected_prefix}{head}.txt"
        actual_txt = args.dir / f"{args.actual_prefix}{head}.txt"

        parse_cmd = [
            sys.executable,
            str(tool_dir() / "parse_actual.py"),
            "--input",
            str(args.actual_csv),
            "--format",
            "uvm-csv",
            "--phase",
            args.phase,
            "--stream",
            args.stream,
            "--head",
            str(head),
            "--out",
            str(actual_txt),
        ]

        compare_cmd = [
            sys.executable,
            str(tool_dir() / "compare.py"),
            "--expected",
            str(expected),
            "--actual",
            str(actual_txt),
            "--row-words",
            str(args.row_words),
        ]
        if args.bit_width is not None:
            compare_cmd.extend(["--bit-width", str(args.bit_width)])

        run(parse_cmd, args.dry_run)
        run(compare_cmd, args.dry_run)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
